### ISSUE TITLE
Support for Data (GetAtt values) in response

### ISSUE THREAD

**Issue by ComaVN** [ryansb/cfn-wrapper-python#6]
Currently, it doesn't seem to be possible to let a custom resource return attributes that can be used by `Fn::GetAtt`, or as output of the stack. Would you be interested in a PR for that?

**Comment by adamchainz** [comment]
It's actually currently possible, just return in `Data` like the sample: https://github.com/ryansb/cfn-wrapper-python/blob/master/cfn_resource.py#L101

**Comment by ComaVN** [comment]
Ah I see it does work. I tried that incorrectly, disregard this.
